appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: gcmHVu6+AoQmPSgDiVOS5VUE8Zp8O25fqD1p0KFZwTObu20PpPitGC45Raco+zrr5i9PrcdcZFqaVDbe+CvR14/I4t8EuFEBN8/THmTM9KsOjc73ROCodvDRfsxZqA7OJH0B47vx6wEccfEr0JvmbsDBSOSeHIAiiDgarfyfNjPWhi1GdokoXMy3dPvza4XJHMYKtRXauo8WUJZ+u+s9hvcfpL1wukIoLTyUjYFvEMf8mrMzwf2cfS8YP0NgDBhYSQiUaJJzWn8HvV705sa9EitYSbCUxRNldm0xJfLU84wJ5qnpfgJBD8rh3/1fRVOkyQp8+vD2NxVKaNuVlNgepUN3i43f2OwNk3xNXVbKM+EzjmagIUcwy/UZRkSjwJIzADqKcAAglq7LcY+bmBtitkZeDGjRGILnhvSr5dJM6eZcXHg+CpCDZnw/xDso1KQkKJthMfnF6zxYnvbSvKZ6P9JaYn6ys7mCzWwJnMaRJIdn1wsDPuejejdQ0xEWxiPs6ZElrfnepnihCy5GxuaRWM18lQ75UvSP3d5GCJXJDq7o/9vBXqm5gDmh6bNN4qY+d2K7QWbsFhGgR/npGcI30r0owc0q/v4QdmucK82bKSsbMQRXBPM5vBr6xuTFFnV+8OqfaL3qD7IzHQFsLTREBtvXVPy2XEhuPWeQ0HYRf/0=
conda_forge_output_validation: false
